### ISSUE TITLE
State of the framework

### ISSUE THREAD

**Issue by MichMich** [kind3r/esp8266-xpressnet-lib#1]
Hi @kind3r,

Awesome to see you working on this ESP version of the library. Exactly what I need. I want to make a PCB for my dad's train. I prefer to use an ESP for future possibilities, but as you know they are currently unsupported.

I was wondering what the state of the library is, if you're still working on it?

Cheers,

Michael.

**Comment by kind3r** [comment]
Hi @MichMich,

Thanks for the interest.

I am working on the libraries (also the z21) in my spare time. They are more or less functional as the original ones but seem to be lacking some features that I would like. You can check out the XpressNet_Z21_ESP.ino example which creates a z21 like command station out of an ESP+RS485 module.

My goal is to have a z21 like device from a low cost esp8266 with a RS485 interface and embed both into a Roco/Fleischmann 10764 Digital amplifier with a Multimouse connected to it.

I am currently working on the S88n support which does not seem to always send the data to Rocrail.

Another issue I'm having (also present in the original library) is that the commands sent by the Multimouse are ignored (because they are not addressed to us I presume) and thus not sent further on the network. On the other hand, Multimouse recognises commands sent from the network.

Any sugestions are welcome.

Emanuel.

**Comment by MichMich** [comment]
Great. Thanks for the info! If I'm not mistaken you are using SoftwareSerial to communicate with the max485 chip, right? I can't find the code which defines the pins. Are they fixed? Or am I misunderstanding the integration?

**Comment by kind3r** [comment]
Pins are defined in [esp8266-XpressNet.h#L54](https://github.com/kind3r/esp8266-xpressnet-lib/blob/master/esp8266-XpressNet.h#L54): **XNetRS485_RX**, **XNetRS485_TX**. Normaly you should be able to override them in your scetch before including the xpressnet lib. The control pin you can specify in XpressNetClass::start. 

I use a modified 9 bit SoftwareSerial version, [espsoftwareRS485](https://github.com/kind3r/espsoftwareRS485). Also, my RS485 shield had reverse functionality of the control pin (RX was on HIGH and TX on LOW) so I added the XControlReverse parameter to XpressNetClass::start.

**Comment by MichMich** [comment]
Awesome! Thanks.

**Comment by kind3r** [comment]
Also, I discovered later that Auto TX control worked just as well on my RS485 shield so now I don't even use the control pin :)

**Comment by MichMich** [comment]
Which shield do you use?

**Comment by kind3r** [comment]
[SparkFun WiFi Shield - ESP8266](https://www.sparkfun.com/products/13287) in combination with [LinkSprite RS485 Shield V2.1](http://linksprite.com/wiki/index.php5?title=RS485_Shield_V2.1_for_Arduino).

Also have a few of [3.3V Auto RS485 to LvTTL RS232 Transceiver Converter SP3485 Module](https://www.aliexpress.com/item/3pcs-3-3V-Auto-RS485-to-LvTTL-RS232-Transceiver-Converter-SP3485-Module-for-esp8266-raspberry-pi/32784567601.html) waiting to be tested as soon as my 12V to 3.3V regulators arrive.

**Comment by MichMich** [comment]
Thanks. I've successfully used [this board](https://www.waveshare.com/rs485-board-5v.htm) to control the trainer using an Arduino nano. I'm now working on a PCB with the MAX485 integrated which allows me to plug in an Arduino nano or WeMos D1 Mini.

**Comment by MichMich** [comment]
I ended up just using the Nano which was enough for my project. If you are interested:
http://michaelteeuw.nl/tagged/trainautomator
